python train.py --name main_pretrain --dataset ogbg-molmuv_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molmuv_01/model.pt --roc_auc --batch_size 128 --num_accumulation_steps 4 --num_epochs 32 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molhiv_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molhiv_01/model.pt --batch_size 128 --num_accumulation_steps 4 --num_epochs 32 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-moltoxcast_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-moltoxcast_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-moltox21_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-moltox21_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molbbbp_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molbbbp_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molbace_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molbace_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molclintox_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molclintox_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molsider_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molsider_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-mollipo_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-mollipo_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molesol_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molesol_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
python train.py --name main_pretrain --dataset ogbg-molfreesolv_main --pretrained_model experiments/ogbg-molpcba/pretrain_for_ogbg-molfreesolv_01/model.pt --batch_size 64 --num_accumulation_steps 1 --num_epochs 100 --warmup_proportion 0.5 --amp --device cuda:0
